stages:
 - Build
 - Quality
 - Package

image: openjdk:8-jre-alpine

before_script:
 - apk add --no-cache curl unzip nodejs nodejs-npm

build:
  stage: Build
  script:
   - cd js
   - npm install
   - npm run build
  artifacts:
    paths:
    - js/spgverein.js

sonarqube:
  stage: Quality
  script:
   - curl -O http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
   - unzip sonar-runner-dist-2.4.zip
   - ./sonar-runner-2.4/bin/sonar-runner -Dsonar.projectKey=de.schrieveslaach.nextcloud.spgverein -Dsonar.sources=. -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONARQUBE_TOKEN

package:
  stage: Package
  script:
   - apk add --no-cache tar
   - tar --exclude='js/node_modules' --exclude='.git' --transform 's,^,spgverein/,' -cvf spgverein.tar.gz *
  artifacts:
    paths:
    - spgverein.tar.gz

