stages:
 - Build
 - Package

image: alpine:edge

before_script:
 - apk add --no-cache curl unzip nodejs nodejs-npm

build-backend:
  stage: Build
  script:
    - apk add --no-cache composer php7-zip php7-xmlreader curl
    - composer install
    # Patch spout until PR has been merged: https://github.com/box/spout/pull/735
    - curl -o vendor/box/spout/src/Spout/Writer/ODS/Manager/WorksheetManager.php https://raw.githubusercontent.com/schrieveslaach/spout/25742181f889487c570e817c258778a94b37f223/src/Spout/Writer/ODS/Manager/WorksheetManager.php
  artifacts:
    paths:
      - vendor/**

build-frontend:
  stage: Build
  script:
   - npm ci
   - npm run build
  artifacts:
    paths:
    - build/**

package:
  stage: Package
  script:
   - apk add --no-cache tar
   - mkdir spgverein
   - cp -r appinfo/ spgverein/
   - cp -r build/ spgverein/
   - cp -r css/ spgverein/
   - cp -r fonts/ spgverein/
   - cp -r img/ spgverein/
   - cp -r js/ spgverein/
   - cp -r l10n/ spgverein/
   - cp -r lib/ spgverein/
   - cp -r templates/ spgverein/
   - cp -r vendor/ spgverein/
   - cp -r CHANGELOG.md spgverein/
   - cp -r README.md spgverein/
   - cp -r COPYING spgverein/
   - tar  -cvzf spgverein.tar.gz spgverein/
  artifacts:
    paths:
    - spgverein.tar.gz

