stages:
 - Test
 - Build
 - Package

test-parser:
  stage: Test
  image: rust
  script:
   - cargo test

build-parser-x86_64-unknown-linux-gnu:
  stage: Build
  image: rust
  services:
   - docker:19.03.12-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: "overlay2"
  script:
   - apt -qq update
   - apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common > /dev/null
   - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
   - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
   - apt -qq update
   - apt install -y docker-ce > /dev/null
   - cargo install --git https://github.com/schrieveslaach/cross.git --branch docker-remote
   - cross build --release --target x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/spg-parser

build-parser-armv7-unknown-linux-gnueabihf:
  stage: Build
  image: rust
  services:
   - docker:19.03.12-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: "overlay2"
  script:
   - apt -qq update
   - apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common > /dev/null
   - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
   - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
   - apt -qq update
   - apt install -y docker-ce > /dev/null
   - cargo install --git https://github.com/schrieveslaach/cross.git --branch docker-remote
   - cross build --release --target armv7-unknown-linux-gnueabihf
  artifacts:
    paths:
      - target/armv7-unknown-linux-gnueabihf/release/spg-parser

build-backend:
  stage: Build
  image: alpine:edge
  script:
    - apk add --no-cache composer php7-zip php7-xmlreader curl
    - composer install
    # Patch spout until PR has been merged: https://github.com/box/spout/pull/735
    - curl -o vendor/box/spout/src/Spout/Writer/ODS/Manager/WorksheetManager.php https://raw.githubusercontent.com/schrieveslaach/spout/25742181f889487c570e817c258778a94b37f223/src/Spout/Writer/ODS/Manager/WorksheetManager.php
  artifacts:
    paths:
      - vendor/**

build-frontend:
  stage: Build
  image: alpine:edge
  script:
   - apk add --no-cache curl unzip nodejs nodejs-npm
   - npm ci
   - npm run test:unit
   - npm run build
  artifacts:
    paths:
    - build/**

package:
  stage: Package
  image: alpine:edge
  script:
   - apk add --no-cache tar
   - mkdir spgverein
   - cp CHANGELOG.md spgverein/
   - cp -r appinfo/ spgverein/
   - cp -r fonts/ spgverein/
   - cp -r img/ spgverein/
   - cp -r l10n/ spgverein/
   - cp -r lib/ spgverein/
   - cp -r templates/ spgverein/
   - cp -r vendor/ spgverein/
   - cp -r CHANGELOG.md spgverein/
   - cp -r CHANGELOG.de.md spgverein/
   - cp -r README.md spgverein/
   - cp -r COPYING spgverein/
   - cp -r build/css/ spgverein/
   - cp -r build/js/ spgverein/
   - cp target/armv7-unknown-linux-gnueabihf/release/spg-parser spgverein/lib/Repository/parser-armv7l
   - cp target/x86_64-unknown-linux-gnu/release/spg-parser spgverein/lib/Repository/parser-x86_64
   - tar  -cvzf spgverein.tar.gz spgverein/
  artifacts:
    paths:
    - spgverein.tar.gz

