stages:
 - Build
 - Package

image: alpine:edge

before_script:
 - apk add --no-cache curl unzip nodejs nodejs-npm

build-backend:
  stage: Build
  script:
    - apk add --no-cache composer php7-zip php7-xmlreader curl
    - composer install
    # Patch spout until PR has been merged: https://github.com/box/spout/pull/735
    - curl -o vendor/box/spout/src/Spout/Writer/ODS/Manager/WorksheetManager.php https://raw.githubusercontent.com/schrieveslaach/spout/25742181f889487c570e817c258778a94b37f223/src/Spout/Writer/ODS/Manager/WorksheetManager.php
  artifacts:
    paths:
      - vendor/**

build-frontend:
  stage: Build
  script:
   - cd js
   - npm ci
   - npm run build
  artifacts:
    paths:
    - js/spgverein.js

package:
  stage: Package
  script:
   - apk add --no-cache tar
   - tar --exclude='js/node_modules' --exclude='.git' --transform 's,^,spgverein/,' -cvzf spgverein.tar.gz *
  artifacts:
    paths:
    - spgverein.tar.gz

