stages:
 - Quality

image: openjdk:8-jre-alpine

before_script:
 - apk update
 - apk add curl

sonarqube:
  stage: Quality
  script:
   - curl -O http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
   - unzip sonar-runner-dist-2.4.zip
   - ./sonar-runner-2.4/bin/sonar-runner -Dsonar.projectKey=de.schrieveslaach.nextcloud.spgverein -Dsonar.sources=. -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONARQUBE_TOKEN

