stages:
 - Build
 - Package

image: alpine:edge

before_script:
 - apk add --no-cache curl unzip nodejs nodejs-npm

build-backend:
  stage: Build
  script:
    - apk add --no-cache composer
    - composer install
  artifacts:
    paths:
      - vendor/**

build-frontend:
  stage: Build
  script:
   - cd js
   - npm ci
   - npm run build
  artifacts:
    paths:
    - js/spgverein.js

package:
  stage: Package
  script:
   - apk add --no-cache tar
   - tar --exclude='js/node_modules' --exclude='.git' --transform 's,^,spgverein/,' -cvzf spgverein.tar.gz *
  artifacts:
    paths:
    - spgverein.tar.gz

